
version: 2

models:
  - name: data_assurance_metrics
    description: "DBT Assurance metrics"
    columns:
      - name: id
        description: "Result Reports from running data assurance"
        tests:
          - unique
          - not_null

  - name: report_view
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
